name: bendium
description: A Chrome extension for talking to Bender.
version: 2.0.0
author: George Lesica <george.lesica@workiva.com>
homepage: https://github.com/georgelesica-wf/bendium

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  js: ^0.6.0
  meta: ^1.0.2
  over_react: ^1.9.0
  pubspec: ^0.1.1
  react: ^4.0.0
  w_common: ^1.2.0
  w_flux: ^2.10.1

dev_dependencies:
  build_runner: ^1.0.0
  build_test: ^0.10.2
  build_web_compilers: ^0.4.0
  dart_style: ^1.0.7
  test: ^1.0.0

transformers:
  - bendium
  - dart_sass_transformer
  - dart_to_js_script_rewriter
  - over_react
  - $dart2js:
      minify: true
      csp: true
  - test/pub_serve:
      $include: test/**_test.dart
